ALTER TABLE "Matter" ADD COLUMN "groupProgress" JSON;

ALTER TABLE "FirmSettings" ADD COLUMN "noMovementDays" INTEGER NOT NULL DEFAULT 7;
ALTER TABLE "FirmSettings" ADD COLUMN "defaultGroupExpectedDays" INTEGER NOT NULL DEFAULT 7;
ALTER TABLE "FirmSettings" ADD COLUMN "groupGraceDays" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "FirmSettings" ADD COLUMN "agingDays" INTEGER NOT NULL DEFAULT 30;
